name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 如果你的 Node.js 版本低于 16.9.0，你可能需要手动安装 corepack，npm install -g corepack
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
      - name: Fix lint issues
        run: pnpm run lint:fix
      - uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84
        with:
          commit-message: "chore: apply automated lint fixes"
